### ISSUE TITLE
使用lcpkg时，如何指定v142工具集来编译？

### ISSUE THREAD

**Issue by lizhuoqi** [lc-ui/lcui-quick-start#1]
使用`lcpkg run start`，第一个步骤的configure无法通过。

提示`error MSB8020: 无法找到 v141_xp 的生成工具(平台工具集 =“v141_xp”)。若要使用 v141_xp 生成工具进行生成，请安装 v141_xp 生成工具。`

本机环境为vs2019，工具集仅安装了v142，如何将项目从v141_xp升级到v142.

**Comment by lc-soft** [comment]
lcpkg 现在只是个下载器，文件都来自 GitHub 上对应版本的发行版附件。

你可以试试修改项目配置，禁用全程序优化。

https://github.com/lc-soft/LCUI/issues/222#issuecomment-681864989
