### ISSUE TITLE
xmake run app 报错

### ISSUE THREAD

**Issue by mcl44** [lc-ui/lcui-quick-start#19]
如图
![image](https://github.com/lcui-dev/lcui-quick-start/assets/92066763/4cd0ef83-d27f-46e3-ba1d-0a3fd8afc0b3)

**Comment by lc-soft** [comment]
升级 xmake 版本试试？或者删掉 xmake.lua 文件里的 `includes("@builtin/xpack")` 和 `xpack("app")` 配置块。
