### ISSUE TITLE
build报错：@lcui/react-icons/dist/style.css: File does not exists

### ISSUE THREAD

**Issue by mcl44** [lc-ui/lcui-quick-start#20]
如图
![image](https://github.com/lcui-dev/lcui-quick-start/assets/92066763/64b39b8d-24ee-4cac-bc0b-9d84362f1183)

**Comment by lc-soft** [comment]
有运行 `npm install` 命令安装依赖包吗？`E:\dev\lcui-quick-start` 目录内是否有 node_modules 目录？

**Comment by mcl44** [comment]
非常抱歉，忘记npm install了。
lcui build仍然报错
![image](https://github.com/lcui-dev/lcui-quick-start/assets/92066763/d00ba08e-8cc5-4dcc-8536-7f5356b68053)

**Comment by lc-soft** [comment]
看错误是因为 LCUI 代码库没下载，等我有空再改下 README 文档，补充 git submodule 的初始化命令。

你先试试用 `lcui create my-lcui-app` 命令来创建项目吧，它会自动执行项目初始化所需的一些命令。

**Comment by mcl44** [comment]
lcui脚手架创建的示例项目，lcui build报错如下
![image](https://github.com/lcui-dev/lcui-quick-start/assets/92066763/64770818-5dc6-4e77-81f9-72ca4f4d6199)
似乎是rc文件有问题？

**Comment by lc-soft** [comment]
"file not found: Visual" 后面的部分呢？

**Comment by mcl44** [comment]
![image](https://github.com/lcui-dev/lcui-quick-start/assets/92066763/ed4ac56e-8cad-4839-873c-e991be28d34e)
如图，并没有后面的部分

**Comment by lc-soft** [comment]
那把 xmake.lua 里的  `add_files("version.rc")` 删掉吧

**Comment by mcl44** [comment]
非常感谢，示例运行成功了

**Comment by lc-soft** [comment]
对于报错 "file not found: Visual" 的问题，可以试试运行 `xmake -v` 命令，看看详细的构建参数和输出

**Comment by mcl44** [comment]
好的，非常感谢 :smile:

**Comment by mcl44** [comment]
> 对于报错 "file not found: Visual" 的问题，可以试试运行 `xmake -v` 命令，看看详细的构建参数和输出

应该是我的vs有问题，报错是一堆编译链接的命令，没看懂

**Comment by lc-soft** [comment]
> > 对于报错 "file not found: Visual" 的问题，可以试试运行 `xmake -v` 命令，看看详细的构建参数和输出
> 
> 应该是我的vs有问题，报错是一堆编译链接的命令，没看懂

把完整的输出内容贴出来看看呗？

**Comment by mcl44** [comment]
![image](https://github.com/lcui-dev/lcui-quick-start/assets/92066763/fb2670e3-5ff1-4c95-b705-de690ab71a7b)
如图
