### ISSUE TITLE
无法编译阿，报错：includes("vendor/LCUI/xmake.lua") cannot find any files!

### ISSUE THREAD

**Issue by mecctor** [lc-ui/lcui-quick-start#21]
xmake之后就出现
checking for platform ... windows
checking for architecture ... x64
checking for Microsoft Visual Studio (x64) version ... 2019
checking for Microsoft C/C++ Compiler (x64) version ... 19.29.30154
error: unknown target(lcui) for app.deps!
warning: includes("vendor/LCUI/xmake.lua") cannot find any files!

**Comment by lc-soft** [comment]
项目改用子模块引用依赖库源码了，README.md 文档还没更新说明。

你运行以下命令试试：

```
git submodule sync --recursive
git submodule update --init --recursive
```
