### ISSUE TITLE
脱坑的又回来了😁unknown option '--mode' 

### ISSUE THREAD

**Issue by fxqy** [lc-ui/lcui-quick-start#3]
这次至少好一点了😁😂，安装好了vs2015、vcpkg、lcpkg，但是卡在运行了，帮忙解决下
error: unknown option '--mode'
```
PS D:\lcui-quick-start> lcpkg run start --mode debug
error: unknown option '--mode'
PS D:\lcui-quick-start>
```
![image](https://user-images.githubusercontent.com/42601163/102704158-a7b1ee80-42b2-11eb-90c7-7edf4f7e15e3.png)

**Comment by lc-soft** [comment]
lc-ui/lcui-router-app#2
