### ISSUE TITLE
尝试用mingw-w64编译，但运行报错找不到DLL

### ISSUE THREAD

**Issue by MrThanlon** [lc-ui/lcui-quick-start#8]
- ucrtbased.dll
- VCRUNTIME140D.DLL
- VCOMP140.DLL

**Comment by lc-soft** [comment]
下载安装 Visual C++ Redistributable Package 试试？
https://www.microsoft.com/zh-CN/download/details.aspx?id=48145

**Comment by MrThanlon** [comment]
> 下载安装 Visual C++ Redistributable Package 试试？ https://www.microsoft.com/zh-CN/download/details.aspx?id=48145

已经安装了2015-2022，但没用，卸载（不卸载会提示已安装更新的版本）后安装2015版本也不行

**Comment by lc-soft** [comment]
> > 下载安装 Visual C++ Redistributable Package 试试？ https://www.microsoft.com/zh-CN/download/details.aspx?id=48145
> 
> 已经安装了2015-2022，但没用，卸载（不卸载会提示已安装更新的版本）后安装2015版本也不行

看上去 Visual C++ Redistributable Package  并不包含 debug 版的 dll，你可尝试以下方法：

- 切换为 release 模式编译
- 手动下载这些 dll 然后复制到系统目录
- 用 mingw-w64 重新编译 LCUI 源码
